name: "CI"

on: push

env:
  SESSION_SECRET: secret-secret-secret

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Typecheck
        run: bun run types:check

      - name: lint
        run: bun run lint:check

      - name: format
        run: bun run format:check
