name: "CI"

on: push

env:
  SESSION_SECRET: secret-secret-secret

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Typecheck
        run: npm run types:check

      - name: lint
        run: npm run lint:check

      - name: format
        run: npm run format:check
